apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ps-mern-cy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-ps-mern-cy
  template:
    metadata:
      labels:
        app: backend-ps-mern-cy
    spec:
      containers:
      - name: profile-microservice
        image: asia-south1-docker.pkg.dev/round-folio-413206/profile-service/profile-srvc:latest
        ports:
          - containerPort: 3002
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: MONGO_URL
---
apiVersion: v1
kind: Service
metadata:
  name: profileservice-be-service
spec:
  selector:
    app: backend-ps-mern-cy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: LoadBalancer